name: camera
description: A Flutter plugin for integrating Camera Access.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      web:
        default_package: camera_web

dependencies:
  camera_platform_interface:
    path: ../camera_platform_interface
  camera_web:
    path: ../camera_web
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  meta: ^1.8.0
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.3
  very_good_analysis: ^4.0.0+1
