name: image_compositor
description: A Flutter package which adds image compositing support via web workers

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.21.7
  very_good_analysis: ^4.0.0+1
